name: Deploy apps/client to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Branch yawe

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare site
        run: |
          mkdir site
          cp -r apps/client/* site/

          # Make public/index.html the homepage
          if [ -f site/public/index.html ]; then
            cp site/public/index.html site/index.html
            cp site/index.html site/404.html || true
          fi

          # Disable Jekyll
          touch site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
